### ISSUE TITLE
Create multiple FTP connections

### ISSUE THREAD

**Issue by AshEdwardsDesign** [sergi/jsftp#107]
Hi there,

I was wondering is there a way (or plans) to allow us to specify the number of FTP connections 'jsftp' makes? Some FTP tools allow us to set a number of connections (parallel file uploads).

This could be handy for large projects or just to cut down on upload time?

(I'm a user of grunt-ftp-deploy which is built on jsftp - I asked the same question there however the response was that it would need to be supported in the underlying 'jsftp')

Thanks! :)

Ash

**Comment by raldred** [comment]
+1 for this to happen

**Comment by ImanMh** [comment]
+1, I need that too

**Comment by sergi** [comment]
Looks like a pretty important feature for you guys, I'll start working on it soon. Thanks for the feedback!

**Comment by raldred** [comment]
@sergi great! I'd love to help but haven't got a clue where to begin.
