### ISSUE TITLE
Multiple file downloads from server fails after first download.

### ISSUE THREAD

**Issue by satishjhanwer** [sergi/jsftp#108]
Hi there,

In one of my requirements, I was trying to download multiple csv files from ftp server and parse these files into json object and store it into mongodb. I was facing bad sequence of command error. logs attached in file. 

Steps to reproduce
1. Connect to ftp and list down remote folder.
2. Filter only csv files.
3. Download the filtered csv files.

Thanks

![image](https://cloud.githubusercontent.com/assets/2142954/4898600/7a0d2a6a-6412-11e4-8e4a-fc72f5928d27.png)

**Comment by louiepiol** [comment]
I got the same issue but in reading multiple csv files, reading the first was successful but not the other csv.
```
var getArray = [];
files.forEach(function (file) {
  if (file.type !== '1' && path.extname(file.name) === '.csv') {
    getArray.push(function(cb) {
     c.get(file.name, './server/csvdata/' + file.name, function (hadErr, socket) {
       if (hadErr) {
        console.error('There was an error retrieving the file.');
       } else {
          socket.on("data", function(csv) {
            console.log(csv.toString())
          });
          socket.on("close", function(hadErr) {
            if (hadErr)
            console.log('There was an error retrieving the file.');
          });
          socket.resume();
          checkIfDone();
       }
       cb();
     });
    });
  }
});
async.series(getArray);
```
Is there any way without creating a new instance for every file? 
Any ideas? Thanks.

**Comment by satishjhanwer** [comment]
@louiepiol 

I have tried what @sergi  mentioned and it worked for me. You should try the same approach.

Thanks

**Comment by louiepiol** [comment]
See on my sample code that I already tried what @sergi mentioned, but there's a problem on reading multiple files continuously.
