### ISSUE TITLE
Information about last modification

### ISSUE THREAD

**Issue by mbatista** [sergi/jsftp#112]
I would like to suggest a few improvements:

1) To be able to get information about last modification of files when using the ls command. I believe this can be done using raw commands for specific file paths, however I would have to make a request for every file just so I know which ones interest me, instead of filtering the single request ls result. Can this be done?

2) Even though I don't think this is possible due ftp limitations, it would be awesome to be able to know the date when the file was added to that directory.

**Comment by sergi** [comment]
I think this is out of the scope of a lightweight FTP library like this one, thanks.
