### ISSUE TITLE
Blocks on OVH hosting

### ISSUE THREAD

**Issue by Robert-W** [sergi/jsftp#113]
Hi, 

  I am using jsftp in a grunt plugin I have created and some of the people using it have reported issues uploading files to OVH.com.  I am linking the ticket below as I am not sure what's going on and am hoping you could possibly shed some light on this.  They have reported that the plugin will work on the same set of files on a different server but won't work on OVH.com.  Here is the link for the open issue (https://github.com/Robert-W/grunt-ftp-push/issues/15).  @mpiffault uploaded a screenshot of a wireshark printout that seems to show a bad passive command coming prematurely from the server.  It will upload a few files and then hangs on a random file, and does not always hang on the same file.

Thanks in advance and any insight would be greatly appreciated.

**Comment by sergi** [comment]
Follow up at https://github.com/Robert-W/grunt-ftp-push/issues/15
