### ISSUE TITLE
Ftp.get not triggering on data

### ISSUE THREAD

**Issue by M44rtenz** [sergi/jsftp#114]
I'm trying to download a file from the server, but socket.on("data") is not triggering. With this code I only see test 1 in the console.

```javascript
ftp.get(path, function(err, socket){
	if (err){
		console.log("Error: " + err);
	} else {
		console.log("test 1");
		socket.on("data", function(data){
			console.log("test 2");
		});
		
		socket.on("close", function(hadErr){
			console.log("test 3");
		});
	}
});
```

**Comment by sergi** [comment]
Hi @M44rtenz, you are missing the call to `socket.resume`. Check out the [example:https://github.com/sergi/jsftp#ftpgetremotepath-callback] in the README
