### ISSUE TITLE
503 Bad Sequence of commands

### ISSUE THREAD

**Issue by SWGFL** [sergi/jsftp#118]
I am using grunt-ftp-deploy to upload my files to the server, but it mostly doesn't work due to this error.

The FTP log shows the following:

pasv
227 Entering Passive Mode (37,128,134,116,250,78)
stor reports.view.php
150 Opening data channel for file upload to server of "/test/application/reports/reports.view.php"
226 Successfully transferred "/test/application/reports/reports.view.php"
cwd /test/application/reports/javascript
250 CWD successful. "/test/application/reports/javascript" is current directory.
pasv
227 Entering Passive Mode (37,128,134,116,250,79)
stor gauge.d3.js
150 Opening data channel for file upload to server of "/test/application/reports/javascript/gauge.d3.js"
pasv
227 Entering Passive Mode (37,128,134,116,250,80)
226 Successfully transferred ""
stor reports.js
503 Bad sequence of commands.
disconnected.

Seems to send the PASV command before it has received confirmation of the last transfer. Most of the time it does this after transferring the first file, but sometimes it will get through 20 or 30 files before this error. Any ideas?

**Comment by SWGFL** [comment]
@zonak suggests it could be a proxy problem, which I am using a proxy server. No probs using FileZilla from the same machine.

**Comment by sergi** [comment]
Do you have the same problem with 1.5.1?

**Comment by zonak** [comment]
Currently the mentioned task is at `1.3.1` - are there any significant api changes or we can just move to the latest?

**Comment by sergi** [comment]
@zonak there shouldn't be any differences, just internal improvements. That being said, please do test it before you put in on production.

**Comment by gkontos** [comment]
I had this problem when transferring files to a filezilla server.  I saw the following within the server logs: 

```
> stor /include/header.html
> 150 Opening data channel for file upload to server of "/include/header.html"
> pasv
> 227 Entering Passive Mode (10,53,40,63,197,233)
> 226 Successfully transferred ""
> stor /index.html
> 503 Bad sequence of commands.
```

This happens more or less randomly.  I was able to fix this issue by changing the processFile function in ftp_push.js to include an additional PASV command : 

```javascript
var processFile = function processFile (err) {
      if (err) {
        grunt.log.warn(messages.fileTransferFail(file.dest, err));
      } else {
        grunt.log.ok(messages.fileTransferSuccess(file.dest));
      }

      ++index;
      // If there are more files, then keep pushing
      if (index < files.length) {
        file = files[index];
     // additonal pasv command to ensure that the server is ready to receive put command.
        server.raw.pasv(function(err,data) {
       	 grunt.log.ok('code ' + data.code);
       });
        server.put(grunt.file.read(file.src, { encoding: null }), file.dest, processFile);
        
      }
```

**Comment by zonak** [comment]
This is most likely a network issue and usually a proxy that causes it.

I am an active use of `grunt-ftp-deploy` and have no issues of the kind.

Unfortunately not being able to reproduce the issue makes any changes hard.

**Comment by SWGFL** [comment]
@gkontos that is the exact problem I had, and @zonak yes I am using a proxy.

**Comment by gkontos** [comment]
@SWGFL I'm not using a proxy, but there is all kinds of weirdness on our network.  So it could be a network issue.

**Comment by SWGFL** [comment]
@gkontos FileZilla works perfectly though, thats how I worked out what the problem was, I compared the logs.

**Comment by zonak** [comment]
Network issues should probably be looked into with `jsftp` which is what this plugin is based on.

**Comment by fily55** [comment]
Hi @zonak ,

I'm having the same issue. I'm using grunt-ftpsync which uses this. 

It only happens to me when I am sending up a lot of files. If you create over 100 files and try to FTP them all up in one go, I wonder will you get the same issue? 

The only thing I noticed is that the sequence of response code changes when it gives the error. 
Another words, it is doing the following sequence:
227
150
226
227
150
226

This is all fine but then it does the following.
227
150
227
226
503.

I'm not an expert in FTP but this is the only change I can see in the sequence of commands.

**Comment by evanplaice** [comment]
Ref: https://github.com/evanplaice/node-ftpsync/issues/27

**Comment by DVassilev** [comment]
@sergi I'm experiencing this issue too when I try to rename a large number of files. Any way to resolve it?
