### ISSUE TITLE
ls encoding problem

### ISSUE THREAD

**Issue by gkTim** [sergi/jsftp#119]
Hi,

I have some problems when a file in a directory contains some umlauts and specialchars and I perform a 'ls' operation.
In my case I have problems with the chars 'öäüß€'

I've changed the following code:

```javascript
listing += data.toString('binary');
```

to

```javascript
listing += data.toString('utf-8');
```

Now the chars are correct, but I'm not sure if this will produce some other errors.

Has anyone an idea how to fix this problem correctly?

**Comment by sergi** [comment]
@gkTim can you try with the latest version (1.5.2)? It should be fixed. Please reopen the issue if it isn't.
