### ISSUE TITLE
Error while unziping file server side

### ISSUE THREAD

**Issue by deepak-manwal** [sergi/jsftp#120]
I am able to connect successfully and can transfer file to server using this module. But don't have any idea how to unzip file after transferring it. So i am using _unzip_ command

I am getting the following error:

    Ftp.raw.unzip('test.zip',function(hadError, data){
                ^
    TypeError: Object function () { return runCmd.apply(self, arguments); } has no method 'unzip'

**Comment by sergi** [comment]
Hi @deepak-manwal. FTP doesn't have unzip functionality. You should look at node libraries or modules for that.
