### ISSUE TITLE
Cannot switch to old mode now.

### ISSUE THREAD

**Issue by hellboy81** [sergi/jsftp#129]
I am trying to upload file using piping from request stream to ftp put socket stream.

In resume  I got 

```
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:748:11)
    at IncomingMessage.Readable.resume (_stream_readable.js:733:3)
```

```js
ftp.getPutSocket(remotePath, function (err, writableSocket) {
   writableSocket.on('close', function (err) {
         if (err) return callback(err)

         pool.release(ftp)
         return cb()
   })

   req.pipe(writableSocket) // Transfer from request to the remote file 
   req.resume(writableSocket) // ERROR Cannot switch to old mode now.
})
```

I am not sure how can I use it right way.

Node v0.10.30

**Comment by sergi** [comment]
Hi! Thanks for this report, as it lead to fixing a potential bug in jsftp. As for your code, `req.pipe` should already resume the stream, so there is no need to use the `req.resume(...)`. A semi-explanation of what's happening is here: https://nodejs.org/api/all.html#all_class_stream_readable and here: http://stackoverflow.com/questions/18306954/cannot-switch-to-old-mode-now-node-js-apn-module-error-in-tls-connect-functi

Of course, switch to Node.js 0.12 or 4.x if you can. Apparently they handle this situation more gracefully.

Let me know if that helps, and if it doesn't please reopen the issue!
