### ISSUE TITLE
ReferenceError: require is not defined(for var Net = require('net') and  var JSFtp= require("jsftp"))

### ISSUE THREAD

**Issue by bipinmaurya** [sergi/jsftp#130]
I had downloaded the 'jsftp-master.zip' file and extracted the zip file using jsftp.js file in my existing web application.From one of the jsp file I am calling one javascript method mentioned below,
..................................................
var JSFtp = require("jsftp");
function uploadFiles(){
	var sourcefile="C:/Users/IBM_ADMIN/Documents/SametimeFileTransfers/Evergreen Hits Of Laxmikant Pyarelal.7z";
	var destDir="/rchgsa-p1/03/fmtprjct/uploadtest";
	var server="abcd.com";
	var user="abc";
	var port=21;
	var passwrod="pqr";
	var ftpServer = new JSFtp({
		  host:server,
		  user:user,
		  port:port, 
		  pass:passwrod,
		  debugMode:true
		});
	ftpServer.auth(user, passwrod, function(hadErr) {
		    if (!hadErr)
		    alert("auth succesfull")
	});
	ftpServer.put(sourcefile, destDir, function(hadError) {
		  if (!hadError)
		    console.log("File transferred successfully!");
		});
}
....................................................
While running in firefox browser I am getting error
ReferenceError: require is not defined for var net = require('net')

I am very much new to this api, can any one please help me to setup this api. I felt that It required some more dependent library but I don't know what are the library needed and from where I can download them.

Thanks in advance.

**Comment by sergi** [comment]
Hi @bipinmaurya , jsftp is built to be run in the server using Node.js, not in the browser.
