### ISSUE TITLE
Caught exception: Error: spawn mkdir ENOENT

### ISSUE THREAD

**Issue by jmzoda** [sergi/jsftp#131]
Hi @sergi 
I followed your proposal and I tried with the latest version 1.5.2 of jsftp (without adding my code for  special characters with accents). 

What I did : 
- npm clone of your project
- pointed my ftp server on it
- launched with npm test 
- here is the result : 
  ...\JSFTP-1.5.2\jsftp>npm test

> jsftp@1.5.2 test JSFTP-1.5.2\jsftp
> mocha -R spec -t 5000

child_process: customFds option is deprecated, use stdio instead.

Caught exception: Error: spawn mkdir ENOENT
...\JSFTP-1.5.2\jsftp\test\jsftp_test.js:49
      server.stop();
            ^
TypeError: Cannot read property 'stop' of undefined
    at process.<anonymous> (...\JSFTP-1.5.2\jsftp\test\jsftp_test.js:49:13)
    at process.emit (events.js:129:20)
    at process._fatalException (node.js:236:26)
npm ERR! Test failed.  See above for more details. 
- fixed the code 
  describe("jsftp test suite", function() {
  process.on('uncaughtException', function(err) {
    console.log('Caught exception: ' + err);
    if(server) { <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< start of hack
      server.stop();
    }<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end of hack
  });
- started npm test again

d:\MyProjects\SVN.BETV.V2\BETV.DEPLOY.WEBMEDIA.EMAILING.JSFTP-1.5.2\jsftp>npm te
st

> jsftp@1.5.2 test d:\MyProjects\SVN.BETV.V2\BETV.DEPLOY.WEBMEDIA.EMAILING.JSFTP
> -1.5.2\jsftp
> mocha -R spec -t 5000

child_process: customFds option is deprecated, use stdio instead.

Caught exception: Error: spawn mkdir ENOENT
  jsftp test suite
    V test initialize bad host (2255ms)
    V test initialize
    V test parseResponse with mark
    V test parseResponse with no mark
    V test send function
    V test parseResponse with ignore code
    V test invalid password
    V test getFeatures
    V test print working directory
    V test switch CWD
    V test switch to unexistent CWD
    V test passive listing of current directory
    V test passive listing of nonexisting directory
Caught exception: AssertionError: [object Object]
    1) test ftp node stat
    V test create and delete a directory
    V test create and delete a directory containing a space
    V test create and delete a file (99ms)
    V test save a remote copy of a local file (65ms)
    V test passing a dir instead of file path to put should callback with error

```
V test streaming put (52ms)
V test rename a file (73ms)
V test get a file
V test get a file and save it locally
V test get a big file stream (68ms)
V test put a big file stream (234ms)
V test put a big file stream fail
V test get fileList array
V test reconnect
V test attach event handlers: connect
```

Caught exception: AssertionError: Error: 503 Bad sequence of commands.
    2) test PASV streaming: Copy file using piping
    V Test that streaming GET (RETR) retrieves a file properly
    V Test that streaming GET (RETR) fails when a file is not present
    V Test that streaming PUT (STOR) stores a file properly
    V Test that streaming PUT (STOR) fails when a file is not present
    V Test that onConnect is called
Caught exception: AssertionError: false == true
    3) Test for correct data on ls 1
    V Test raw method with PWD
    V Test raw method with HELP
    V Test keep-alive with NOOP (5001ms)
    - Test handling error on simultaneous PASV requests {#90}
    V test set binary type
    V test listing a folder containing special UTF characters

  38 passing (13s)
  1 pending
  3 failing

  1) jsftp test suite test ftp node stat:
     Uncaught

Don't hesitate.

**Comment by sergi** [comment]
What FTP server are you using? Would it be possible to make an anonymous account for me to test in it?
