### ISSUE TITLE
Support for SFTP

### ISSUE THREAD

**Issue by flesler** [sergi/jsftp#157]
Hi, does it support SFTP? I checked the README and see no explicit mention.
Thanks

**Comment by RubenCordeiro** [comment]
I don't think it supports SFTP. Maybe @sergi can confirm?

**Comment by sonidodespacio** [comment]
Hello @sergi, is there a some kind of interest in supporting SFTP ? Just curious.

Thanks,
Regards.

**Comment by dbrugne** [comment]
+1

**Comment by CBox** [comment]
+1

**Comment by fithwith** [comment]
+1

**Comment by jayagl** [comment]
For anyone desperately in need of SFTP support: I added minimal support for FTP over TLS/SSL in this [branch](https://github.com/jayagl/jsftp). Also see [pull request](https://github.com/sergi/jsftp/pull/178) for said branch. The changes are quite simple and easy to understand.
