### ISSUE TITLE
Files Not Coming Back in Full Form on get()

### ISSUE THREAD

**Issue by SteveyPugs** [sergi/jsftp#192]
Here is the scenario that I am running. I have a zip file (about 800KB) that come in everyday during the week that I need to parse through. So I go the FTP to retrieve the file and I have to parse through it. Getting the file is fine but in both cases below the length is always different every 1 out of 5 to 10 runs. It is very random. Any insight would be great.

```
var mt_ftp = new jsftp({
    host: "HOST",
    user: "USER",
    pass: "PASS"
});
```

```
mt_ftp.list("*.gz", function(err, res){
    var list = res.split("\n");
    async.eachSeries(list, function(r, callback){
        if(r.length > 0){
            var filename = r.substring(55, r.length).replace("\r","");
            mt_ftp.get(filename, function(err, socket) {
                var str = "";
                socket.on("data", function(d) {
                    str += d.toString();
                })
                socket.on("close", function(hadErr) {
                    if(hadErr){
                        console.log(hadErr);
                    }
                });
                socket.on("end", function(){
                    console.log(str.length)
                });
                socket.resume();
            });
        }
        else{
            callback();
        }
    }, function(err){
        if(err) console.log(err);
    });
});
```

```
mt_ftp.list("*.gz", function(err, res){
    var list = res.split("\n");
    async.eachSeries(list, function(r, callback){
        if(r.length > 0){
            var filename = r.substring(55, r.length).replace("\r","");
            mt_ftp.get(filename, filename, function(err){
                if(err) callback(err);
                else{
                    var filePreZIP = fs.readFileSync(filename);
                    console.log(filePreZIP.length)
                }
            });
        }
        else{
            callback();
        }
    }, function(err){
        if(err) console.log(err);
    });
});
```

**Comment by batjko** [comment]
Have you thought of using `mt_ftp.ls()` instead of `.list`? Gives you a pre-parsed array of file objects which I found a lot easier to deal with.

**Comment by SteveyPugs** [comment]
Everytime I do that I get this:

```
C:\Test>node index.js
[ { name: 'in the past 24 hours.', type: 0, time: NaN, size: '3' } ]
```

Code is:

```
mt_ftp.ls(".", function(err, res){
	console.log(res)
});
```

Could I possibly be doing something wrong?

I def have 7 files in there now.

**Comment by batjko** [comment]
That's weird. When I tried the `.ls()` method I got an array of proper file objects, as expected.
But your output looks like it's picking up a piece of a stream or something...? Sorry, no idea.

**Comment by SteveyPugs** [comment]
@batjko yeah I had no clue either.

I have switched to node-ftp, it works fine for my casing.

**Comment by sergi** [comment]
This is very strange @SteveyPugs, and I am sorry it caused you trouble. I know you just switched, but do you have some details of your setup? e.g ftp server, nodejs version?

**Comment by SteveyPugs** [comment]
Thanks for the response @sergi what exact details would you need to know ftp wise (only think I can think is ftp vs sftp, haha). I was using node v4 LTS which I think at the time was 4.4.7? I also am using Windows 7 x64 and I believe the ftp is on Windows 2K8 server.
