### ISSUE TITLE
invalid host names stop the server 

### ISSUE THREAD

**Issue by jairoGilC** [sergi/jsftp#195]
When I  create a new connection ` var ftp = new JSFtp({"host": "test.talia.neta", "port": 21, "user": "anonymous","pass": "1234"});` but the host name is incorrect generate the following error and the server stop.

	Error: getaddrinfo ENOTFOUND test.talia.neta test.talia.neta:21
	    at errnoException (dns.js:27:10)
	    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

	npm ERR! Linux 3.19.0-65-generic
	npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
	npm ERR! node v4.4.2
	npm ERR! npm  v3.9.5
	npm ERR! code ELIFECYCLE
	npm ERR! PYS-FORM@0.0.0 start: `node ./bin/www`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the PYS-FORM@0.0.0 start script 'node ./bin/www'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the PYS-FORM package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node ./bin/www
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs PYS-FORM
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls PYS-FORM
	npm ERR! There is likely additional logging output above.

Is posible that only generate a error but the server still running?

**Comment by sergi** [comment]
Yeah, check out  this test in `jsftp_test.js`:
```
  it('test initialize bad host', function(next) {
    var ftp2 = new Ftp({
      host: 'badhost',
      user: 'user',
      port: 21,
      pass: '12345'
    });

    ftp2.on('error', function(err) {
      assert.equal(err.code, 'ENOTFOUND');
      next();
    });
  });
```
