### ISSUE TITLE
Parsing of file listings

### ISSUE THREAD

**Issue by hgupta9** [sergi/jsftp#242]
Hi, this is Harsh from the [FluentFTP](https://github.com/hgupta9/FluentFTP) project. This project seems to be missing file listing parsing, ie. when users call ftp.list, the raw strings are returned to the users instead of properties like name, path, date modified, size, permissions, etc.

Would you like me to port our file listing parsers from C# to JS? I have extensive experience with both languages.

**Comment by sergi** [comment]
Hi @hgupta9, JsFtp is using https://github.com/sergi/parse-listing to do that. Is that what you are referring to?

**Comment by hgupta9** [comment]
Yes its what I'm referring to, I'm actually writing to ask if you would like more support for other OS's. Eg. OpenVMS, machine listings, etc. It can be ported from FluentFTP to jsftp.
