### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by blackshadev** [sergi/jsftp#247]
Is the project still active?

I see the open issuers growing, I have multiple DeprecationWarnings when using default examples from your README.md.
If this project is infact bleeding dead, does anybody know an good FTP package?

**Comment by c0d0g3n** [comment]
About the DeprecationWarnings: the code is updated on Github but not (yet) on npm. I can't help you with the other questions, as I just found out about this project myself. I didn't find a similar and up-to-date package either.

**Comment by sergi** [comment]
Hi, this project is not dead. I am just very busy with personal stuff lately. I'll update several things this week.

Sorry for not responding before!
