### ISSUE TITLE
put() doesn't check when the file has finished uploading

### ISSUE THREAD

**Issue by telmotrooper** [sergi/jsftp#265]
I uploaded a 17 MB file to my server using put() and the function called the callback function many seconds before the file finished uploading.

The example provided in the documentation goes as follows:
```
ftp.put(buffer, 'path/to/remote/file.txt', function(hadError) {
  if (!hadError)
    console.log("File transferred successfully!");
});
```

I'm guessing the callback function is called as soon as the upload starts, differently than what the example suggests. I couldn't find a way to check if the file has finished uploading in the documentation.

**Comment by sergi** [comment]
Can you please run your program in debug mode? i.e. `DEBUG=jsftp:* node yourprogram.js`. and post the output?

Thanks!

**Comment by telmotrooper** [comment]
@sergi Hello, I just did what you asked, here's the log: https://pastebin.com/QpRRcV4f

As you can see, the message "File uploaded to the FTP server." comes before the server returns "226-File successfully transferred".

That's what the code looks like: https://pastebin.com/riHs4NZA

Thank you for your time.

**Comment by telmotrooper** [comment]
Somehow it works now even though I didn't even update the dependencies, but you can see in the log that it wasn't working back when I posted it.

I guess you can close the issue for now, if you can't reproduce the issue.
