### ISSUE TITLE
PUT with local path

### ISSUE THREAD

**Issue by simonh1000** [sergi/jsftp#272]
I'm trying to call 
```
ftp.put(fullLocalPath, remoteFilePath, err => {
```
where fullLocalPath is something like 
`/home/simon/code/sync/nodejs/ftp-deploy/test/local/folderA/folderB/emptyC/folderD/test-inside-d-1.txt`

I'm ending up with ` Error: 553 Could not create file.` Do I have in fact to do a directory traversal on the client and remote side and only put by filename without any 'path/to/directory/filename.txt'?

The answer seems to be no, as I don't seem to have problems with some ftp sites, but I cannot get it to work with my local vsftpd server that I use for testing

**Comment by sergi** [comment]
Hi @simonh1000 ,

No, that should just work. An 553 error is commonly a matter of permissions on the remote end. If you still think that it's jsftp's fault, it would be great if you try to reproduce as a unit test.

Thanks!
