### ISSUE TITLE
raw command size does not return intended result

### ISSUE THREAD

**Issue by logicminds** [sergi/jsftp#275]
The following code 

```
function get_size_from_ftp(ftp, file_path) {
  return new Promise((resolve, reject) => {
    ftp.raw("size", file_path, (err, data) => {
      if (err) {
        return console.error(err);
        reject(err);
      }
      console.log(data); // Show the FTP response text to the user
      resolve(data.text);
    });
  });
}
```
Yields the correct object but the result code is still part of the text when it should not be

`{ code: 213, text: '213 812', isMark: false, isError: false }`

The correct result should be
`{ code: 213, text: '812', isMark: false, isError: false }`

**Comment by sergi** [comment]
Hi @logicminds,

This works as expected. Why shouldn't the code be part of `text`?

**Comment by logicminds** [comment]
My expectation is that I should not have to parse out the code from the text value.  If everyone has to do `data.text.split(' ').pop()` why not just add this to the library.  Especially since the return code is already part of the data object.

**Comment by sergi** [comment]
It's a valid point, but `text` in this case refers to the complete text of the response. The assumption that everyone is not interested in it is unfounded, given that many people uses it to 'echo' the ftp server response, and if they then want to include the code, many people would have to add the code to the text.

Also, something like `data.text.substr(4)` is not that terrible to write.

In the future, to not break compatibility, maybe an extra field called `description` could be added to the object, containing the text without the code.
