### ISSUE TITLE
ERROR: read ECONNRESET

### ISSUE THREAD

**Issue by nicopenaredondo** [sergi/jsftp#289]
Hi, any solution with the error below ? 

![image](https://user-images.githubusercontent.com/3615451/43063823-9cb92770-8e8f-11e8-86ab-f9652f100ee9.png)

**Comment by nicopenaredondo** [comment]
![image](https://user-images.githubusercontent.com/3615451/43063835-af059882-8e8f-11e8-9bbf-b12eb6310d87.png)

**Comment by nicopenaredondo** [comment]
forgot to quit the session upon initializing.

**Comment by taozi0818** [comment]
how do you resolve it ? @nicopenaredondo
