### ISSUE TITLE
ECONNRESET Error when FTP Server/ TCP connection is dropped

### ISSUE THREAD

**Issue by munirdalkaya** [sergi/jsftp#294]
Hi Sergi,

may I ask you to add a  this.on("error", dbgResponse); to the Ftp initialization function to catch TCP disconnects? Otherwise the node instace crashes when the FTP server drops the  connection (Error: read ECONNRESET). This fix/workaround helped: 

function Ftp(cfg) {
	console.log("START JSFTP")
  this.host = cfg.host || FTP_HOST;
  this.port = cfg.port || FTP_PORT;
  this.user = cfg.user || "anonymous";
  this.pass = cfg.pass || "@anonymous";
  // True if the server doesn't support the `stat` command. Since listing a
  // directory or retrieving file properties is quite a common operation, it is
  // more efficient to avoid the round-trip to the server.
  this.useList = cfg.useList || false;

  this.commandQueue = [];

  EventEmitter.call(this);

  this.on("data", dbgResponse);
  this.on("error", dbgResponse);

  this._createSocket(this.port, this.host);
}

**Comment by uholland** [comment]
+1

**Comment by DesignMonkey** [comment]
+1
