### ISSUE TITLE
delete file / folder function

### ISSUE THREAD

**Issue by lucav90** [sergi/jsftp#297]
hi,

there is the function to delete a folder or a file?

**Comment by scottclayton** [comment]
In case anyone else ends up on this ticket, a raw call with `dele` is the one that worked for me. If you like promises, here's mine:

```js
const deleteFileFromFTP = (fileName) =>
  new Promise((resolve, reject) =>
    Ftp.raw('dele', fileName, (err) => {
      if (err) return reject(err)

      return resolve()
    }),
  )
```

I found `dele` on this list of ftp commands: https://www.nsftools.com/tips/RawFTP.htm
