### ISSUE TITLE
How to use active, not passive mode?

### ISSUE THREAD

**Issue by netwjx** [sergi/jsftp#49]
How to use active, not passive mode?

**Comment by prasunsultania** [comment]
Is active FTP supported by this library?

**Comment by throrin19** [comment]
+1

**Comment by elvizcacho** [comment]
+1

**Comment by EvanCarroll** [comment]
Why is this issue closed? Can't we label it WON'T FIX or something if we're rejecting the idea of a full featured FTP client?
