### ISSUE TITLE
No Progress Data on upload

### ISSUE THREAD

**Issue by ragheed** [sergi/jsftp#53]
While uploading a file through "put", the object returned by "progress" event doesn't have "transferred" data.

Example:
this is always returned when i console.log progress data:

``` JSON
{ filename: '/test.zip',
  action: 'put',
  total: 268295573,
  transferred: undefined }
```

**Comment by kivervinicius** [comment]
any other comment about this?

**Comment by PaykomanVll** [comment]
sergi, can you please help? I need this to build a progressbar of put (send exist file to other server).
All solutions that are here written, will not work and your script return allwas 'transfered: undefined' and i use the current version.

Then i tried to modify the emitProgress Function but nothing tests will work :(
I have added an entry to the object with test: data.test, andthe put function send now data.test with content 'hello world' but on ftp.on("progress" myfun) is nothing to see =(

a chunk is ok, i need not exact data, the final call will at the end say is all ok or not.

Im very happy if you can create a little update and include this.

Best regards, stefan
