### ISSUE TITLE
About SSL

### ISSUE THREAD

**Issue by pyprism** [sergi/jsftp#57]
How to use secure connection ?

**Comment by jkryl** [comment]
I added support for AUTH TLS command in my fork https://github.com/jkryl/jsftp . The difference compared to solution suggested above is that with my fix the clients first connects to the FTP server through plain FTP protocol and after that it "upgrades" the plain connection to TLS by means of AUTH TLS command. I tested the code with sstur/nodeftpd implementation but only very lightly. But it seems to work. BDD tests and documentation changes are missing, if anyone wants to take the code further to make it fully ready for submitting a PR before I have time to do that, that would be great.

**Comment by warpdesign** [comment]
Any reason why this hasn't been merged into the original rep? @jkryl @sergi 

I'd need TSL support but unfortunately, it's still not merged into the rep. I saw your fork @jkryl but it seems to behind the original rep, missing a few important fixes.

**Comment by jkryl** [comment]
@warpdesign I'm not using jsftp package anymore. Someone would have to pick up my old fix and prepare it for PR (rebase & test cases).  Though before doing that, I would recommend to check with @sergi if he is willing to accept such fix to avoid wasted effort.
