### ISSUE TITLE
Copy from Server to Server.

### ISSUE THREAD

**Issue by myoung69** [sergi/jsftp#64]
Hello,

I am having trouble getting jsftp to do what i would like it to.

I am trying to code a script that copies a file or directory from one ftp connection to another ftp connection using a separate machine from either ftp connections.

any examples to get me started on streaming a file from one server to another would be very much appreciated.

**Comment by jpattisoninc** [comment]
I just finished a queue based module utilizing https://github.com/bbc/sqs-consumer. Basically read all file to a queue and the consumer will handle the file transport. As FTP seems loaded with failure points by it's very nature, you'll have to do a bit of work to make sure your files are intact for each step in the transport process.
