### ISSUE TITLE
Send multiple files

### ISSUE THREAD

**Issue by efsantana** [sergi/jsftp#66]
I'm trying to send multiple files to the ftp server and I'm usually losing connection after sending the first file. What's the best way to send more than one file to an ftp server.

I'm getting the files as base 64 strings through web sockets using socket.io and trying to send them using the put method.

**Comment by mrameezraja** [comment]
does anyone was able to solve without creating a new instance for every file?

**Comment by JulienLeal** [comment]
This just happens yet. How I fix it ??

**Comment by juampi92** [comment]
IDK if some of you figured it out, but in I had the same problem, and I tried using a mapSeries instead of parallel. Seems that one FTP session can only do one task at once. If you'd like parallelism, use multiple sessions (or sockets)
