### ISSUE TITLE
Uncaught error if an error happens

### ISSUE THREAD

**Issue by SankaD** [sergi/jsftp#90]
If I provide a non existent host/already existing filename/etc... I get a 

Uncaught Error: getaddrinfo ENOTFOUND
      at errnoException (dns.js:37:11)
      at Object.onanswer [as oncomplete](dns.js:124:16)

Shouldn't it just pass the error as the error parameter?

**Comment by grrenier** [comment]
Hello, I'm trying to execute a raw command "mkd" for a non existing FTP server and I'm getting this error:

    events.js:72
            throw er; // Unhandled 'error' event
                 ^
    Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

How can I manipulate it? Thanks

**Comment by Sampo123** [comment]
Has this proceeded in any way? I'm currently limited to older version and I'm not able or it would be a huge workload for me to upgrade right now but I'm facing the uncaught error problem. If my host cannot be found from DNS, then an uncaught error is propagated to the top of the stack. Which is not nice :(

**Comment by coderade** [comment]
I am having the same problem @Sampo123. 
There is a way to handle the errors like TIMEOUT and ECONNREFUSED?
