### ISSUE TITLE
getting an exception when creating JSFtp

### ISSUE THREAD

**Issue by nraghu99** [sergi/jsftp#98]
i already did  npm install jsftp

and got a response 
npm WARN package.json strong-agent@0.4.9 No repository field.
jsftp@1.3.1 ../../../../node_modules/jsftp
├── once@1.3.0
├── event-stream@3.0.20 (stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, pause-stream@0.0.11, map-stream@0.0.4, split@0.2.10, through@2.3.4)
├── parse-listing@1.1.0 (async@0.2.10)
└── ftp-response-parser@1.0.0 (readable-stream@1.1.13-1)

Here is the code which fails

var fs = require("fs");
var sys  = require("sys");
var jsftp  =  require("jsftp");
var lazy = require("lazy");
var sessionmgrhost =  "10.30.12.15";
var sessionmgrport =  22;
var sessionmgruser  =  "'CDR_User";
var sessionmgrpass = "C/arus02";

var remoteFileDir = " ";
var localFileDir = "/Users/nraghu/Documents/SMFtpFiles";
var ftp = new JSFtp({
    host: sessionmgrhost,
    port : sessionmgrport,
    user : sessionmgruser,
    pass: sessionmgrpass
});

I am getting an error in new JSFtp 
ReferenceError: JSFtp is not defined
    at Object.<anonymous> (/Users/nraghu/Documents/workspace/cdrjs/nodejscdr/fileprocessor_single.js:12:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Please help

**Comment by telmotrooper** [comment]
Found on #210 that you can do:
```
conn.on("error", function(error) {
	console.log(error);
});
```

Still, that doesn't give me any context to properly treat the exception, what would really help me is if I could somehow get the request and response objects (from Express.js) from the request in which the exception was thrown. Is that possible at all?
